### ISSUE TITLE
【APP】バージョンアップ対応

### ISSUE THREAD

**Issue by kohei-okazaki** [kohei-okazaki/work-3g#949]
## 概要
各ライブラリのサポート期限対応のため

## 内容
| 名前 | 変更前 | 変更後 | 備考 |
| ---- | ---- | ---- | ---- |
| Java | 11 | 21 |
| spring | 5.3.0 | 6.1.12 |
| spring-data-commons | 2.7.6 | 3.3.3 |
| spring boot | 2.4.2 | 3.3.3 | spring batchも含む |
| aspect | 1.9.9.1 | 1.9.22.1 |
| jackson | 2.14.1 | 2.17.2 |
| MyBatis | 3.5.11 | 3.5.16 |
| mybatis-spring | 3.0.0 | 3.0.4 |
| thymeleaf | 3.1.2.RELEASE | 3.1.2.RELEASE | thymeleaf-spring５ -> thymeleaf-spring6 |
| commons-lang3 | 3.12.0 | 3.16.0 |

**Comment by hemantgarg1452** [comment]
What's the issue?
